// Clinical reasoning frameworks and reference cards.
// Add new entries here; the drawer will render them automatically.

export const FRAMEWORKS = [
  {
    id: 'vindicate',
    category: 'mnemonics',
    title: 'VINDICATE',
    subtitle: 'Broad differential across categories',
    body: [
      { letter: 'V', label: 'Vascular', notes: 'MI, stroke, DVT, dissection, ischemia' },
      { letter: 'I', label: 'Infectious', notes: 'Bacterial, viral, fungal, parasitic' },
      { letter: 'N', label: 'Neoplastic', notes: 'Primary, metastatic, paraneoplastic' },
      { letter: 'D', label: 'Degenerative / Drugs', notes: 'Age-related, medication side effects' },
      { letter: 'I', label: 'Iatrogenic / Idiopathic', notes: 'Procedure-related; unknown cause' },
      { letter: 'C', label: 'Congenital', notes: 'Structural or genetic anomalies' },
      { letter: 'A', label: 'Autoimmune / Allergic', notes: 'SLE, RA, vasculitis, anaphylaxis' },
      { letter: 'T', label: 'Traumatic / Toxic', notes: 'Injury; poisons, overdoses' },
      { letter: 'E', label: 'Endocrine / Environmental', notes: 'Thyroid, adrenal, DM; heat/cold' },
    ],
  },
  {
    id: 'matched',
    category: 'mnemonics',
    title: 'MATCHED',
    subtitle: 'Alternative systems mnemonic',
    body: [
      { letter: 'M', label: 'Metabolic', notes: 'Electrolytes, glucose, acid-base' },
      { letter: 'A', label: 'Allergic / Autoimmune', notes: 'Hypersensitivity, connective tissue' },
      { letter: 'T', label: 'Toxins / Trauma', notes: 'Medications, exposures, injury' },
      { letter: 'C', label: 'Congenital', notes: 'Genetic, structural' },
      { letter: 'H', label: 'Heme / Endo', notes: 'Blood dyscrasias, hormonal' },
      { letter: 'E', label: 'Endocrine', notes: 'Thyroid, adrenal, pituitary' },
      { letter: 'D', label: 'Drugs', notes: 'Rx, OTC, illicit, herbal' },
    ],
  },
  {
    id: 'anatomic-abdomen',
    category: 'anatomic',
    title: 'Anatomic — Abdominal pain',
    subtitle: 'Work outside-in through every structure',
    body: [
      { label: 'Skin', notes: 'Herpes zoster (shingles)' },
      { label: 'Muscle (wall)', notes: 'Trauma, infection, hernia' },
      { label: 'Nerve', notes: 'Zoster, post-surgical' },
      { label: 'Liver', notes: 'Hepatitis, abscess, mass' },
      { label: 'Gallbladder', notes: 'Cholecystitis, stones' },
      { label: 'Pancreas', notes: 'Pancreatitis, mass' },
      { label: 'Spleen', notes: 'Trauma, enlargement' },
      { label: 'Stomach', notes: 'Ulcer, gastritis' },
      { label: 'Small bowel', notes: 'Gastroenteritis, obstruction, IBD, intussusception' },
      { label: 'Appendix', notes: 'Appendicitis' },
      { label: 'Large bowel', notes: 'Infection, diverticulitis, obstruction, IBD' },
      { label: 'GU', notes: 'UTI, stones' },
      { label: 'GYN', notes: 'Ectopic, ovarian cyst/torsion, PID' },
      { label: 'Vessels', notes: 'AAA dissection, mesenteric ischemia, SMA syndrome' },
      { label: 'Intra-abd muscles', notes: 'Abscess' },
      { label: 'Lymph nodes', notes: 'Mesenteric adenitis' },
      { label: 'Extra-abdominal', notes: 'LL pneumonia, MI, DKA, Addisonian crisis' },
    ],
  },
  {
    id: 'mechanism-jaundice',
    category: 'mechanism',
    title: 'Mechanism — Jaundice',
    subtitle: 'Walk the pathway; failure at any step causes disease',
    body: [
      { label: 'RBC breakdown ↑', notes: 'Hemolysis, polycythemia, sepsis' },
      { label: 'Transport to liver', notes: 'Transport protein deficiency' },
      { label: 'Conjugation', notes: 'Gilbert, Crigler-Najjar, physiologic, prematurity, breast milk, sepsis, hypothyroid' },
      { label: 'Transport to intestine', notes: 'Hepatitis, biliary atresia, choledochal cyst, obstruction' },
      { label: 'Enterohepatic recirc ↑', notes: 'Intestinal obstruction, constipation' },
    ],
  },
  {
    id: 'mechanism-anemia',
    category: 'mechanism',
    title: 'Mechanism — Anemia',
    subtitle: '↓ production, ↑ destruction, or blood loss',
    body: [
      { label: '↓ Production', notes: 'Marrow damage (leukemia, drugs, radiation, viruses); nutrient deficiency (Fe, B12, folate); EPO ↓ (renal); Hb synthesis (thalassemia)' },
      { label: '↑ Destruction (extrinsic)', notes: 'Antibody-mediated, mechanical (hypersplenism, endocarditis, DIC)' },
      { label: '↑ Destruction (intrinsic)', notes: 'Abnormal Hb (sickle), membrane (spherocytosis), enzymes (G6PD)' },
      { label: 'Blood loss', notes: 'Overt hemorrhage, occult GI loss, contained space (femur fx)' },
    ],
  },
  {
    id: 'think-metabolic',
    category: 'red-flags',
    title: '"Think metabolic" when...',
    subtitle: 'Clinical clues that shift the differential toward inborn errors',
    body: [
      { label: 'GI', notes: 'Recurrent vomiting, poor feeding, failure to thrive' },
      { label: 'Neuro', notes: 'Lethargy, developmental regression, afebrile seizures' },
      { label: 'Volume/pH', notes: 'Unexplained dehydration, acidosis' },
      { label: 'Sensory', notes: 'Unusual body odor or urine odor' },
      { label: 'Family history', notes: 'Young family member with unexplained death' },
      { label: 'Metabolic labs', notes: 'Hypoglycemia (especially without ketosis)' },
      { label: 'Exam', notes: 'Organomegaly' },
    ],
  },
  {
    id: 'think-genetic',
    category: 'red-flags',
    title: '"Think genetic" when...',
    subtitle: 'When to broaden toward inherited conditions',
    body: [
      { label: 'Dysmorphology', notes: 'Any major dysmorphism, or multiple minor ones' },
      { label: 'Multi-system', notes: '≥2 organ systems involved' },
      { label: 'Growth', notes: 'Failure to thrive, short stature (esp. girls), overgrowth, asymmetric growth' },
      { label: 'Development', notes: 'MR, developmental delay, autism' },
      { label: 'Atypical course', notes: 'Severe ADHD or behavior problems; poor response to appropriate therapy' },
      { label: 'Behavior + dysmorphism', notes: 'Any combination raises suspicion' },
    ],
  },
  {
    id: 'symptom-complex',
    category: 'strategies',
    title: 'Symptom Complex',
    subtitle: 'Pattern-recognition from a small cluster of findings',
    body: [
      { label: 'How', notes: 'Match 2-3 findings against known conditions' },
      { label: 'Strength', notes: 'Fast; matches expert reasoning during interview' },
      { label: 'Limit', notes: 'Requires deep pattern database; risks anchoring and premature closure; DDx often too narrow' },
    ],
  },
  {
    id: 'local-anatomic',
    category: 'strategies',
    title: 'Local Anatomic',
    subtitle: 'Consider every structure at the site of complaint',
    body: [
      { label: 'How', notes: 'Ask: what structures are here? Start from skin, work inward' },
      { label: 'Strength', notes: 'Systematic; catches structures you wouldn\'t recall randomly' },
      { label: 'Limit', notes: 'Misses referred/systemic causes (e.g., lower-lobe pneumonia causing abdominal pain)' },
    ],
  },
  {
    id: 'systems-approach',
    category: 'strategies',
    title: 'Systems Approach',
    subtitle: 'Head-to-toe + hidden systems, or use a mnemonic',
    body: [
      { label: 'How', notes: 'Walk every organ system; add metabolic, allergic, toxic, congenital, heme, endo, drugs' },
      { label: 'Strength', notes: 'Very broad differential' },
      { label: 'Limit', notes: 'Overkill for focal complaints' },
    ],
  },
  {
    id: 'mechanism-approach',
    category: 'strategies',
    title: 'Mechanism Approach',
    subtitle: 'Walk the physiologic pathway; find where it can fail',
    body: [
      { label: 'How', notes: 'Ask "how is this normally made / regulated?" Then ask where each step can break' },
      { label: 'Best for', notes: 'Symptoms tied to biochemical/endocrine pathways (jaundice, anemia, amenorrhea)' },
      { label: 'Strength', notes: 'Elegant; ensures nothing along the pathway is missed' },
    ],
  },
];

export const CATEGORIES = [
  { id: 'strategies', label: 'Strategies', description: 'How to generate a differential' },
  { id: 'mnemonics',  label: 'Mnemonics',  description: 'Broad-category prompts' },
  { id: 'anatomic',   label: 'Anatomic',   description: 'Structure-by-structure lists' },
  { id: 'mechanism',  label: 'Mechanism',  description: 'Physiology-based reasoning' },
  { id: 'red-flags',  label: 'Red flags',  description: 'When to broaden the DDx' },
];
